name: Simulated Cloud Deployemnt 

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-lastest
    steps:
     - name: Checkout Repo
       uses: actions/checkout@v2

     - name: Simulate Deployment
       run:  |
        mkdir -p simulated-server
        cp index.html simulated-server/
        echo "Deployemt complete to simulated-server"
